-- Enable pgvector for semantic search
CREATE EXTENSION IF NOT EXISTS vector;

-- Users profile (extends Supabase auth.users)
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT,
  canvas_access_token TEXT,
  canvas_domain TEXT DEFAULT 'csueastbay.instructure.com',
  peak_energy_window TEXT DEFAULT 'morning',  -- morning/afternoon/evening
  sleep_target_hours FLOAT DEFAULT 7.5,
  sleep_bedtime TIME DEFAULT '23:00',
  wake_time TIME DEFAULT '07:00',
  timezone TEXT DEFAULT 'America/Los_Angeles',
  onboarding_complete BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Courses from Canvas
CREATE TABLE courses (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  canvas_course_id TEXT NOT NULL,
  name TEXT NOT NULL,
  course_code TEXT,
  professor_name TEXT,
  color TEXT,  -- assigned color for UI
  syllabus_text TEXT,  -- parsed syllabus content
  syllabus_parsed BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, canvas_course_id)
);

-- Assignments pulled from Canvas + syllabus parsing
CREATE TABLE assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  course_id UUID REFERENCES courses(id) ON DELETE CASCADE,
  canvas_assignment_id TEXT,
  title TEXT NOT NULL,
  due_date TIMESTAMP WITH TIME ZONE,
  points_possible FLOAT,
  assignment_type TEXT,  -- homework/exam/quiz/project/reading
  difficulty_score FLOAT DEFAULT 0.5,  -- 0-1, estimated by AI
  estimated_hours FLOAT DEFAULT 1.0,   -- AI-estimated completion time
  status TEXT DEFAULT 'pending',  -- pending/in_progress/completed
  source TEXT DEFAULT 'canvas',   -- canvas/syllabus/manual
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- User's tasks (can come from assignments or be manually added)
CREATE TABLE tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  assignment_id UUID REFERENCES assignments(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  description TEXT,
  scheduled_start TIMESTAMP WITH TIME ZONE,
  scheduled_end TIMESTAMP WITH TIME ZONE,
  duration_minutes INTEGER DEFAULT 60,
  energy_required TEXT DEFAULT 'medium',  -- low/medium/high
  status TEXT DEFAULT 'pending',  -- pending/in_progress/completed/skipped
  completed_at TIMESTAMP WITH TIME ZONE,
  added_via TEXT DEFAULT 'manual',  -- manual/ai/siri/canvas
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Daily check-ins (mood + energy + sleep)
CREATE TABLE daily_checkins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  check_date DATE NOT NULL,
  mood_score INTEGER CHECK (mood_score BETWEEN 1 AND 5),
  energy_score INTEGER CHECK (energy_score BETWEEN 1 AND 5),
  sleep_hours FLOAT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, check_date)
);

-- NPC state history
CREATE TABLE npc_states (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  state_date DATE NOT NULL,
  overall_state TEXT NOT NULL,  -- thriving/happy/neutral/tired/stressed/overwhelmed
  energy_level FLOAT,
  mood_score FLOAT,
  tasks_completion_rate FLOAT,
  sleep_score FLOAT,
  streak_days INTEGER DEFAULT 0,
  overdue_count INTEGER DEFAULT 0,
  npc_level INTEGER DEFAULT 1,
  unlocked_items JSONB DEFAULT '[]',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, state_date)
);

-- Growth tracking (tree / NPC idle time)
CREATE TABLE growth_sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  session_start TIMESTAMP WITH TIME ZONE NOT NULL,
  session_end TIMESTAMP WITH TIME ZONE,
  idle_minutes INTEGER DEFAULT 0,
  interrupted BOOLEAN DEFAULT false,
  interruption_count INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Daily insights generated by AI
CREATE TABLE daily_insights (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  insight_date DATE NOT NULL,
  insight_text TEXT NOT NULL,
  quote_text TEXT,
  quote_author TEXT,
  behavioral_pattern TEXT,
  generated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, insight_date)
);

-- Streak tracking
CREATE TABLE streaks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  streak_type TEXT NOT NULL,  -- tasks/growth/checkin/sleep
  current_streak INTEGER DEFAULT 0,
  longest_streak INTEGER DEFAULT 0,
  last_activity_date DATE,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE(user_id, streak_type)
);

-- RLS policies
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE npc_states ENABLE ROW LEVEL SECURITY;
ALTER TABLE growth_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_insights ENABLE ROW LEVEL SECURITY;
ALTER TABLE streaks ENABLE ROW LEVEL SECURITY;

-- Allow users to only access their own data
CREATE POLICY "Users own data" ON profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY "Users own data" ON courses FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users own data" ON assignments FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users own data" ON tasks FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users own data" ON daily_checkins FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users own data" ON npc_states FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users own data" ON growth_sessions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users own data" ON daily_insights FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Users own data" ON streaks FOR ALL USING (auth.uid() = user_id);
