export const demoCourses = [
  {
    id: "course-cs3550",
    name: "CS 3550",
    courseCode: "CS 3550",
    professorName: "Prof. Chen",
    color: "#E8C97A",
    dueThisWeek: 2,
  },
  {
    id: "course-econ102",
    name: "ECON 102",
    courseCode: "ECON 102",
    professorName: "Prof. Alvarez",
    color: "#8BA7D4",
    dueThisWeek: 1,
  },
  {
    id: "course-bio210",
    name: "BIO 210",
    courseCode: "BIO 210",
    professorName: "Prof. Rivers",
    color: "#7EC8A4",
    dueThisWeek: 1,
  },
  {
    id: "course-math230",
    name: "MATH 230",
    courseCode: "MATH 230",
    professorName: "Prof. Patel",
    color: "#C98B6A",
    dueThisWeek: 0,
  },
];

export const demoAssignments = [
  {
    id: "assign-1",
    courseId: "course-cs3550",
    title: "Lab report 4",
    dueDate: "2026-03-23T17:00:00.000Z",
    estimatedHours: 3,
    difficulty: 0.82,
    status: "pending" as const,
    source: "canvas" as const,
  },
  {
    id: "assign-2",
    courseId: "course-bio210",
    title: "Midterm review quiz",
    dueDate: "2026-03-25T20:00:00.000Z",
    estimatedHours: 2,
    difficulty: 0.61,
    status: "pending" as const,
    source: "syllabus" as const,
  },
  {
    id: "assign-3",
    courseId: "course-econ102",
    title: "Market trends reflection",
    dueDate: "2026-03-26T16:00:00.000Z",
    estimatedHours: 1.5,
    difficulty: 0.42,
    status: "pending" as const,
    source: "canvas" as const,
  },
];

export const demoTasks = [
  {
    id: "task-1",
    title: "CS Lab Report",
    courseName: "CS 3550",
    scheduledTime: "09:00",
    endTime: "10:30",
    durationMinutes: 90,
    energyRequired: "high" as const,
    category: "deep_work" as const,
    priority: "urgent_important" as const,
    dueAt: "2026-03-21T17:00:00.000Z",
    labels: ["@canvas", "@deadline-hard"] as const,
    focusTechnique: "Ultradian 90min" as const,
    implementationIntention:
      "When I sit at my desk at 9AM, I will open the lab spec and write the first working function.",
    notes: "Your hardest task today. Peak window is the best shot at finishing it cleanly.",
    progress: 0.32,
    status: "pending" as const,
  },
  {
    id: "task-2",
    title: "Econ Reading",
    courseName: "ECON 102",
    scheduledTime: "10:30",
    endTime: "11:15",
    durationMinutes: 45,
    energyRequired: "medium" as const,
    category: "study_review" as const,
    priority: "important" as const,
    dueAt: "2026-03-23T15:00:00.000Z",
    labels: ["@review-later"] as const,
    focusTechnique: "Review Sprint" as const,
    implementationIntention:
      "When I finish CS, I will annotate Chapter 8 and extract three exam-level concepts.",
    notes: "Best in a secondary block or as an interleaving break between harder subjects.",
    status: "pending" as const,
  },
  {
    id: "task-3",
    title: "Break - Walk route",
    courseName: "Pulse",
    scheduledTime: "12:00",
    endTime: "12:30",
    durationMinutes: 30,
    energyRequired: "low" as const,
    category: "self_care" as const,
    priority: "important" as const,
    dueAt: "2026-03-21T12:00:00.000Z",
    labels: ["@anywhere"] as const,
    focusTechnique: "Time Block" as const,
    implementationIntention:
      "When the deep work block ends, I will step outside before touching my phone.",
    notes: "Movement break. Protect this so the next block doesn't feel like sludge.",
    status: "pending" as const,
  },
  {
    id: "task-4",
    title: "Calc Problem Set",
    courseName: "MATH 230",
    scheduledTime: "13:00",
    endTime: "15:00",
    durationMinutes: 120,
    energyRequired: "high" as const,
    category: "assignment" as const,
    priority: "urgent_important" as const,
    dueAt: "2026-03-22T20:00:00.000Z",
    labels: ["@laptop-only", "@deadline-hard"] as const,
    focusTechnique: "Ultradian 96min" as const,
    implementationIntention:
      "When I reopen the set at 1PM, I will solve questions 4 and 5 before checking Discord.",
    notes: "Two-hour block is pushing it. Interleaving with Econ for 30 minutes would improve retention.",
    status: "pending" as const,
  },
  {
    id: "task-5",
    title: "Reply emails",
    courseName: "Admin",
    scheduledTime: "15:30",
    endTime: "15:50",
    durationMinutes: 20,
    energyRequired: "low" as const,
    category: "admin_life" as const,
    priority: "urgent" as const,
    dueAt: "2026-03-21T18:30:00.000Z",
    labels: ["@quick-win"] as const,
    focusTechnique: "Quick Wins" as const,
    implementationIntention:
      "When I open Gmail, I will clear every professor reply in one pass and leave.",
    notes: "Batch this with printing and office-hours questions to reduce friction.",
    status: "pending" as const,
  },
];

export const demoInsight = {
  title: "Today's insight",
  insight:
    "You complete 80% of high-focus work before 2PM but only 20% after 8PM. Tonight's hardest task should move to tomorrow morning.",
  quote:
    "We are what we repeatedly do. Excellence, then, is not an act but a habit.",
  author: "Will Durant",
};

export const demoEvents = [
  {
    title: "Live Music at The Bistro",
    date: "Tonight",
    time: "8:00 PM",
    location: "Downtown Hayward",
    distance: "0.8 miles",
    cost: "Free",
    source_url: "https://example.com/live-music",
  },
  {
    title: "CSUEB Study Social",
    date: "Friday",
    time: "6:30 PM",
    location: "Pioneer Heights Lounge",
    distance: "On campus",
    cost: "Free",
    source_url: "https://example.com/study-social",
  },
];
